import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/loggedin/Header'
import Slider from '../components/mainpage/Slider'
import Categories from '../components/mainpage/Categories'

export default function Home() {
  return (
    <div className=' antialiased bg-gray-100 min-h-screen'>
      <Head>
        <title>iFlip</title>
        <meta name="description" content="Generated by iflip" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

<Header />

<Slider />

<Categories />

<Footer />

     
     
    </div>
  )
}
