import Head from 'next/head';
import Footer from '../components/Footer';
import Header from '../components/mainpage/Header';
import Slider from '../components/mainpage/Slider';
import Categories from '../components/mainpage/Categories';
import SliderBrands from '../components/mainpage/SliderBrands';
import Product from '../components/mainpage/Product.jsx'

export default function Home() {
  return (

    <div className=' antialiased bg-stone-100 min-h-screen space-y-10'>
      <Head>
        <title>iFlip</title>
        <meta name="description" content="Generated by iflip" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
<Header />

<Slider />

<Categories />

<SliderBrands />

<Product />





<Footer />

     
     
    </div>
  )
}
